const { renderVehicleDiagram } = require('./vehicle-diagram');
const { selectExteriorSequence, EXTERIOR_STATIONS } = require('./photo-sequence');
const labels = {front:'Anteriore',front_right:'Anteriore destro',right:'Fianco destro',rear_right:'Posteriore destro',rear:'Posteriore',rear_left:'Posteriore sinistro',left:'Fianco sinistro',front_left:'Anteriore sinistro',interior_front:'Interni anteriori',interior_rear:'Interni posteriori',dashboard:'Cruscotto'};
function renderIntakePage({ w, settings:s, photos, acceptance, editable, req, helpers:h, terms, privacy }) {
  const {esc,formToken,input,select,orderLabel,fmtDate}=h;
  const mechanic=req.session.user.role==='mechanic',sequence=selectExteriorSequence(photos),positions=new Map(sequence.stitchPhotos.map((photo,i)=>[String(photo.id),i]));
  const knownMarks=photos.flatMap(photo=>Array.isArray(photo.damage_marks)?photo.damage_marks.map(mark=>({...mark,photo_id:photo.id})):[]);
  const photoCards=photos.map(photo=>`<article class="intake-photo" data-photo-id="${photo.id}" data-document-id="${photo.document_id}" data-category="${esc(photo.category)}" data-station="${esc(photo.station)}" data-label="${esc(labels[photo.station]||photo.station)}" data-sequence="${positions.has(String(photo.id))}" data-sequence-order="${positions.get(String(photo.id))??''}"><button type="button" class="intake-photo-preview" data-preview-photo aria-label="Apri foto ${esc(labels[photo.station]||photo.station)}"><img src="/tablet/work-orders/${w.id}/documents/${photo.document_id}" alt="${esc(labels[photo.station]||photo.station)}" loading="lazy"></button>${editable?`<button type="button" class="intake-photo-delete" data-delete-photo aria-label="Elimina foto">×</button>`:''}<span>${esc(labels[photo.station]||photo.station)}</span></article>`).join('');
  const capture=`<section class="card intake-capture"><div class="capture-vehicle"><div class="section-heading"><h2>Sagoma e danni</h2><span class="badge" data-photo-coverage>${sequence.coveredStations}/8 aree</span></div><div class="vehicle-figure">${renderVehicleDiagram({interactive:true,captured:photos.filter(p=>p.category==='exterior').map(p=>p.station),marks:knownMarks})}</div><p class="intake-hint">Tocca il punto del danno sulla vista corretta, poi fotografa la zona. I segni rossi vengono salvati insieme alla foto.</p><div class="damage-actions"><button type="button" class="button small" data-undo-damage ${editable?'':'disabled'}>Annulla ultimo segno</button><button type="button" class="button small" data-clear-damage ${editable?'':'disabled'}>Cancella segni nuovi</button><span data-damage-count>0 segni nuovi</span></div></div><div class="camera-panel"><div class="camera-frame"><video id="intake-camera" autoplay playsinline muted></video><canvas id="capture-canvas" hidden></canvas><div id="camera-placeholder">Attiva la fotocamera oppure usa Scegli foto</div></div><div class="camera-controls"><label>Categoria<select id="photo-category"><option value="exterior">Esterni</option><option value="interior">Interni</option><option value="dashboard">Cruscotto</option></select></label><label>Posizione<select id="photo-station">${Object.entries(labels).map(([key,label])=>`<option value="${key}">${label}</option>`).join('')}</select></label><button class="button primary" id="capture-photo" type="button" ${editable?'':'disabled'}>Scatta e salva foto</button><label class="button file-pick">Scegli foto<input id="file-photo" type="file" accept="image/*" capture="environment" ${editable?'':'disabled'}></label><p id="camera-status" role="status">${editable?'Mantieni l’auto intera nell’inquadratura. Per la cucitura usa foto consecutive con zone in comune, stessa altezza e distanza.':'Accettazione bloccata: foto e danni sono in consultazione.'}</p></div></div></section>`;
  const gallery=`<section class="card intake-gallery"><div class="section-heading"><h2>Foto registrate</h2><a class="button" href="/tablet/work-orders/${w.id}/acceptance.pdf?paper=1&send_to_office=1">Invia modulo al PC</a><a class="button" href="/tablet/work-orders/${w.id}/vehicle-sheet" target="_blank" rel="noopener">Scheda veicolo</a><button type="button" id="open-photo-print" class="button primary" ${photos.length?'':'disabled'}>Stampa / invia al PC</button></div><div class="intake-photo-grid" data-plate="${esc(w.plate)}" data-customer="${esc(w.customer)}" data-make="${esc(w.make)}" data-model="${esc(w.model)}" data-order="${w.id}" data-editable="${editable}" data-csrf="${esc(req.session.user.csrfToken)}">${photoCards||'<p class="muted" data-empty-photos>Nessuna foto acquisita.</p>'}</div><nav class="intake-gallery-pager" aria-label="Pagine foto"><button type="button" class="button" data-gallery-prev>← Precedenti</button><span data-gallery-count role="status"></span><button type="button" class="button" data-gallery-next>Successive →</button></nav></section>`;
  const client=`<section class="card intake-client"><h2>Dati cliente</h2>${editable&&!mechanic?`<form method="post" action="/tablet/work-orders/${w.id}/customer" data-client-edit>${formToken(req)}<div class="form-grid">${input('Nome / ragione sociale','name','text',w.customer,true)}${input('Telefono','phone','tel',w.customer_phone,true)}${input('Email','email','email',w.email)}${select('Tipo cliente','kind',[['person','Persona'],['business','Azienda']],w.customer_kind)}</div><button type="button" class="button" data-client-extra-toggle>Indirizzo e dati fiscali →</button><div data-client-extra hidden><div class="form-grid">${input('Codice fiscale','tax_code','text',w.customer_tax_code)}${input('Partita IVA','vat_number','text',w.customer_vat_number)}${input('Indirizzo','address','text',w.customer_address)}</div><label>Note<textarea name="notes">${esc(w.customer_notes||'')}</textarea></label><button type="button" class="button" data-client-extra-toggle>← Dati principali</button></div><button class="button primary" type="submit">Salva dati cliente</button><p data-client-status role="status"></p></form>`:`<p><strong>${esc(w.customer)}</strong></p><p>${esc(w.customer_phone||'Telefono non inserito')} · ${esc(w.email||'Email non inserita')}</p><p class="muted">${mechanic?'Il responsabile gestisce i dati cliente.':'Sblocca Accettazione per correggere i dati.'}</p>`}</section>`;
  const check=(name,text,required=false)=>`<label class="accept-row"><input type="checkbox" name="${name}" ${required?'required':''}>${text}</label>`;
  const signature=`<section class="card intake-signature"><h2>Documenti, consensi e firme</h2>${editable?`<form id="acceptance-form" method="post" novalidate data-work-order="${w.id}" data-csrf="${esc(req.session.user.csrfToken)}" data-terms="${esc(terms)}" data-privacy="${esc(privacy)}"><div class="signature-stepper" data-sign-stepper role="status">Passaggio 1 di 4</div>
<fieldset data-sign-step="0"><legend>Documenti e autorizzazioni</legend><label>Nome del cliente che firma<input name="signed_name" required value="${esc(w.customer)}"></label><div class="document-actions"><button type="button" class="button" data-read-document="terms">Leggi condizioni</button><button type="button" class="button" data-read-document="privacy">Leggi informativa privacy</button></div>${check('terms_accepted','Accetto le condizioni del servizio di riparazione.',true)}${check('privacy_acknowledged','Confermo di aver ricevuto e letto l’informativa privacy.',true)}${check('road_test_authorized','Autorizzo una prova su strada per le verifiche pertinenti (facoltativo).')}</fieldset>
<fieldset data-sign-step="1" hidden><legend>Preferenze email e prezzo</legend><label>Email cliente<input type="email" data-consent-email value="${esc(w.email||'')}" readonly></label><p class="intake-hint">Per modificarla usa Dati cliente. I consensi email sono facoltativi e revocabili.</p>${check('repair_email_consent','Desidero aggiornamenti email su questo intervento.')}${check('marketing_consent','Acconsento alle comunicazioni promozionali email.')}${check('profiling_consent','Acconsento alla profilazione per offerte personalizzate.')}<div class="form-grid">${input('Servizio a prezzo preaccordato (facoltativo)','preagreed_service')}${input('Prezzo IVA inclusa (€)','preagreed_price','number')}</div></fieldset>
<fieldset data-sign-step="2" hidden><legend>Firma per le condizioni</legend><p class="intake-hint">Firma nello spazio. La firma viene conservata cambiando passaggio.</p><label>Firma cliente — condizioni<canvas class="signature-pad" data-signature="terms"></canvas><button type="button" class="button clear-signature">Cancella firma</button></label></fieldset>
<fieldset data-sign-step="3" hidden><legend>Firma per la privacy e salvataggio</legend><label>Firma cliente — informativa privacy<canvas class="signature-pad" data-signature="privacy"></canvas><button type="button" class="button clear-signature">Cancella firma</button></label><p class="intake-hint">Salvando, GO conserva testi e scelte del cliente e blocca l’accettazione.</p></fieldset>
<footer class="intake-sign-controls"><button type="button" class="button" data-sign-prev>← Indietro</button><button type="button" class="button primary" data-sign-next>Avanti →</button><button class="button primary" type="submit" hidden>Salva firme e accettazione</button></footer><p id="acceptance-status" role="status"></p></form>`:`<p class="notice">Accettazione registrata e bloccata.</p><p>Firma del ${acceptance?fmtDate(acceptance.accepted_at):'—'} · prova su strada ${acceptance?.road_test_decision==='authorized'?'autorizzata':'rifiutata'}</p><a class="button primary" href="/tablet/work-orders/${w.id}/acceptance.pdf" target="_blank" rel="noopener">Apri documento firmato</a>`}</section>`;
  const labs=`<section class="card intake-labs"><h2>Vista cilindrica 360° · Labs</h2><p>GO cerca dettagli comuni tra foto vicine, allinea le zone riconosciute e crea una maschera di fusione. La texture viene avvolta su un cilindro ruotabile.</p><p class="intake-hint">Fotografa tutti gli 8 lati; aggiungi scatti intermedi dove manca la sovrapposizione. Carrozzeria lucida, riflessi o prospettive diverse possono richiedere una correzione manuale. Questa vista conserva l’aspetto fotografico, non misura la geometria dell’auto.</p><button id="view-360" class="button primary" type="button" ${sequence.complete?'':'disabled'}>Crea / apri vista cilindrica</button><p data-labs-coverage>${sequence.coveredStations}/8 posizioni acquisite</p></section>`;
  const panels=[['photos','Sagoma e scatto',capture],['gallery','Galleria foto',gallery],['client','Dati cliente',client],...(!mechanic?[['signature','Consensi e firme',signature]]:[]),...(s.labs_3d_enabled?[['labs','Vista 360°',labs]]:[])];
  const requested=String(req.query.panel||'photos'),selected=panels.some(p=>p[0]===requested)?requested:'photos';
  const screenLink=/^\/customer-screen\/[A-Za-z0-9_-]+$/.test(String(req.query.customer_screen||''))?String(req.query.customer_screen):'';
  return `${h.takeFlash(req)}<section class="intake-workspace" data-intake-workspace data-work-order="${w.id}" data-editable="${editable}"><header class="intake-workspace-head"><div><strong>${esc(w.plate)}</strong><span>${esc(orderLabel(w))} · ${esc(w.make)} ${esc(w.model)} · ${esc(w.customer)}</span></div><span class="badge ${editable?'warning':'good'}">${editable?'Accettazione aperta':'Accettazione registrata'}</span><a class="button" href="/tablet/work-orders/${w.id}?mode=view&tab=repair">← Lavoro</a>${s.customer_display_enabled&&!mechanic?`<form method="post" action="/tablet/work-orders/${w.id}/customer-screen">${formToken(req)}<button class="button">Schermo cliente</button></form>`:''}<a class="button" href="/tablet/work-orders/${w.id}/acceptance.pdf?paper=1" target="_blank" rel="noopener">Modulo PDF</a></header>${screenLink?`<p class="notice">Schermo cliente pronto: <a href="${esc(screenLink)}" target="_blank" rel="noopener">Apri sul dispositivo cliente</a></p>`:''}<nav class="intake-workspace-tabs" role="tablist" aria-label="Schede accettazione">${panels.map(([key,label])=>`<button type="button" class="button" role="tab" data-intake-tab="${key}" id="intake-tab-${key}" aria-controls="tablet-intake-${key}" aria-selected="${key===selected}" tabindex="${key===selected?0:-1}">${label}</button>`).join('')}</nav><div class="intake-workspace-stage">${panels.map(([key,label,html])=>`<section class="tablet-intake-panel" role="tabpanel" id="tablet-intake-${key}" aria-labelledby="intake-tab-${key}" ${selected===key?'':'hidden'}>${html}</section>`).join('')}</div></section>`;
}
module.exports = { renderIntakePage, labels };
